paths:
    /orders:
        post:
            operationId: createOrder
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                order:
                                    type: array
                                    items:
                                        type: object
                                        properties:
                                            product:
                                                type: string
                                            size:
                                                type: string
                                                enum:
                                                    - small
                                                    - medium
                                                    - big
                                            quantity:
                                                type: integer
                                                required: false
                                                default: 1
                                        required:
                                            - product
                                            - size
